# Generated by Django 5.2.1 on 2025-05-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AircraftPartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aircraft')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parttype')),
            ],
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('built_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.builtaircraft')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.part')),
            ],
        ),
    ]
