# Generated by Django 5.2.1 on 2025-05-09 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_part_quantity_aircraftpartcompatibility_partusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducedAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.producedaircraft'),
        ),
    ]
