# Generated by Django 5.2.1 on 2025-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_producedaircraft_part_used_in_aircraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='used_in_aircraft',
        ),
        migrations.AddField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ManyToManyField(blank=True, related_name='parts_used', to='accounts.producedaircraft'),
        ),
    ]
