# Generated by Django 5.2.1 on 2025-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_part_used_in_aircraft_part_used_in_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ManyToManyField(blank=True, related_name='parts', to='accounts.aircraft'),
        ),
    ]
