# Generated by Django 5.2.1 on 2025-05-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_part_used_in_aircraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='used_in_aircraft',
        ),
    ]
