# Generated by Django 5.2.1 on 2025-05-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_part_used_in_aircraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builtaircraft',
            name='parts',
        ),
        migrations.AlterField(
            model_name='partusage',
            name='built_aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='accounts.builtaircraft'),
        ),
    ]
