# Generated by Django 5.2.1 on 2025-05-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_builtaircraft_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtaircraft',
            name='parts',
            field=models.ManyToManyField(to='accounts.part'),
        ),
    ]
