# Generated by Django 5.2.1 on 2025-05-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_builtaircraft_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_parts', to='accounts.aircraft'),
        ),
        migrations.AlterField(
            model_name='part',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_by_type', to='accounts.aircraft'),
        ),
    ]
