# Generated by Django 5.2.1 on 2025-05-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_part_used_in_aircraft_alter_part_aircraft_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='part',
            name='used_in_aircraft',
        ),
        migrations.AlterField(
            model_name='part',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aircrafttype'),
        ),
        migrations.AddField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ManyToManyField(related_name='parts', to='accounts.aircraft'),
        ),
    ]
