# Generated by Django 5.2.1 on 2025-05-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_part_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtaircraft',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aircrafttype'),
        ),
    ]
