# Generated by Django 5.2.1 on 2025-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_aircraft_aircraft_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ManyToManyField(blank=True, related_name='parts', to='accounts.aircraft'),
        ),
    ]
