# Generated by Django 5.2.1 on 2025-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_part_used_in_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='used_in_aircraft',
            field=models.ManyToManyField(blank=True, to='accounts.builtaircraft'),
        ),
    ]
